"""empty message

Revision ID: 15748d17c4ff
Revises: 
Create Date: 2018-06-04 13:34:35.819779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15748d17c4ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
