"""empty message

Revision ID: 433d8ad66ef1
Revises: ac5583e5351f
Create Date: 2018-06-06 16:07:50.382332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '433d8ad66ef1'
down_revision = 'ac5583e5351f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    # ### end Alembic commands ###
